version: "3.9"

services:
  app:
    build: .
    image: ghcr.io/nguyenthanhtoan2103/finance-tracker:latest
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/finance-tracker
      REDIS_HOST: redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo_data:
