# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications

name: CI/CD Backend to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker login GHCR
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u nguyenthanhtoan2103 --password-stdin

      # 3. Build Docker image backend
      - name: Build backend Docker image
        run: |
          full_image="ghcr.io/nguyenthanhtoan2103/finance-tracker-backend:latest"
          docker build -t $full_image ./backend

      # 4. Push backend Docker image
      - name: Push backend Docker image
        run: |
          full_image="ghcr.io/nguyenthanhtoan2103/finance-tracker-backend:latest"
          docker push $full_image

      # 5. Deploy to VPS
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/Finance-tracker/backend
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u nguyenthanhtoan2103 --password-stdin
            docker-compose pull
            docker-compose down
            docker-compose up -d --build


