# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications

name: CI/CD to Windows VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/nguyenthanhtoan2103/finance-tracker:latest ./backend

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/nguyenthanhtoan2103/finance-tracker:latest

      - name: Deploy to Windows VPS via SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          privateKey: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          command: |
            cd C:\\finance-tracker
            docker compose pull
            docker compose up -d --build
