# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications

name: CI/CD to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # 1. Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------------
      # 2. Debug all secrets
      # -------------------------------
      - name: Debug all input values
        run: |
          set -eux
          echo "===== DEBUG INPUT VALUES ====="
          echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
          echo "VPS_USER: ${{ secrets.VPS_USER }}"
          if [ -n "${{ secrets.VPS_PRIVATE_KEY }}" ]; then
            echo "VPS_PRIVATE_KEY first 30 chars: $(echo "${{ secrets.VPS_PRIVATE_KEY }}" | head -c 30)"
            echo "VPS_PRIVATE_KEY length: $(echo -n "${{ secrets.VPS_PRIVATE_KEY }}" | wc -c)"
          else
            echo "VPS_PRIVATE_KEY is missing!"
          fi
          if [ -n "${{ secrets.GHCR_PAT }}" ]; then
            echo "GHCR_PAT first 10 chars: $(echo "${{ secrets.GHCR_PAT }}" | head -c 10)"
          else
            echo "GHCR_PAT is missing!"
          fi
          echo "===== END DEBUG ====="
      # -------------------------------
      # 3. Build Docker image
      # -------------------------------
      - name: Build Docker image
        run: |
          set -eux
          docker build -t ghcr.io/nguyenthanhtoan2103/finance-tracker:latest ./backend
      # -------------------------------
      # 4. Login to GitHub Container Registry
      # -------------------------------
      - name: Login to GHCR
        run: |
          set -eux
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # -------------------------------
      # 5. Push Docker image
      # -------------------------------
      - name: Push Docker image
        run: |
          set -eux
          docker push ghcr.io/nguyenthanhtoan2103/finance-tracker:latest
      # -------------------------------
      # 6. Deploy to Ubuntu VPS via SSH key
      # -------------------------------
      - name: Deploy to Ubuntu VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Starting deployment on Ubuntu VPS..."
            cd /home/Finance-tracker
            echo "Pulling latest Docker images..."
            docker compose pull
            echo "Starting containers..."
            docker compose up -d --build
            echo "Deployment completed!"
